### ISSUE TITLE
Decompilation problem

### ISSUE THREAD

**Issue by Mhzpoo** [avast/retdec#1064]
Hello,

For classes, I sometimes need to decompile executable files but when I try to use retdec it always say "architecture not supported" (using retdec-decompiler.py). Which kind of surprise me to be honest as I tried on different computers (Macbook Pro Retina 13'' Mid-2017 on MacOS Monterey, on a virtual machine on that Mac (VMWare Fusion Ubuntu 20.04) and on a Honor Magicbook 15 on Windows 11) that aren't that old.

I also noticed in the README.md file that when downloading a prebuilt package, I'm supposed to have a "retdec-decompiler" when downloading the Ubuntu or MacOS version, or a "retdec-decompiler.exe" when downloading the Windows version. But I only have the python file which gives me the message written above.
![image](https://user-images.githubusercontent.com/97026219/155412240-6e117621-61af-4cb6-b623-05439575f0c8.png)

What could I do to repare that problem?

Thanks in advance

**Comment by silverbacknet** [comment]
You need to use one of the nightly builds, since the last release there's been 2 years of big changes and improvements. Your binary should work after that.

https://github.com/avast/retdec#automated-teamcity-builds
