### ISSUE TITLE
Move to new LLVM version

### ISSUE THREAD

**Issue by PeterMatula** [avast/retdec#110]
Version of LLVM we use is pretty old (`3.9.1`). We should move to the new LLVM sooner rather than later.

**Comment by MerovingianByte** [comment]
Wouldn't it be possible to talk to the LLVM guys to provide more options to disable optimizations and stuff so that retdec can use vanilla LLVM instead of hacking it? Maybe it would save time in the long run. I mean, I'm just curious, not my business.

**Comment by s3rvac** [comment]
@MerovingianByte Frankly speaking, I do not see this as realistic. We have many changes throughout the entire codebase, and their conditional inclusion would seriously clutter the code. Never say never, though :-).

**Comment by s3rvac** [comment]
LLVM 6.0 [is out](http://lists.llvm.org/pipermail/llvm-dev/2018-March/121675.html).

**Comment by s3rvac** [comment]
LLVM 7.0 [is out](http://lists.llvm.org/pipermail/llvm-announce/2018-September/000080.html).

**Comment by s3rvac** [comment]
LLVM 8.0 [is out](https://lists.llvm.org/pipermail/llvm-announce/2019-March/000082.html).

**Comment by sskras** [comment]
Are other changes not linked to this commit?

**Comment by PeterMatula** [comment]
This was fixed by merging `llvm-8` branch in `llvm` repo: https://github.com/avast/llvm/commit/82632c555520b4f490d33c799aa1256817d734d2
and in `retdec` repo: https://github.com/avast/retdec/commit/7a2018bb4dce191242cd7382390993ff6a8ab865
