### ISSUE TITLE
readme says .exe release only have .py 

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [avast/retdec#1122]
nothing on the online readme says it require to install stinky python to run this as well... as i can't install garbageware here, so oh well... it would be better to know BEFORE downloading.

**Comment by PeterMatula** [comment]
Python was required by older `v4.0` releases. If you read the current `master` Readme, it described the current state that did not require Python, but didn't correspond with what you downloaded in the `v4.0` release package.

Anyway, we recently released `v5.0` that does not require Python, so there is not discrepancy anymore.
