### ISSUE TITLE
How to use the pre-installed LLVM package?

### ISSUE THREAD

**Issue by yurivict** [avast/retdec#1130]
It appears that currently depending on LLVM_LOCAL_DIR configure either uses the externally provided LLVM source tree or downloads it.

How to use pre-installed LLVM without rebuilding it?

**Comment by Nitr0-G** [comment]
These args
```
cmake -DCMAKE_INSTALL_PREFIX="YOUR PATH TO RETDEC DIR" -G"Visual Studio 16 2019" -DRETDEC_ENABLE_ALL=ON -DCMAKE_BUILD_TYPE=ALL ..
```

**Comment by PeterMatula** [comment]
You **can** clone [avast/llvm](https://github.com/avast/llvm), build it, and then use it in RetDec compilation by specifying `LLVM_LOCAL_DIR=<path to cloned repo>`. Then, you can make changes to this LLVM sources and when you recompile RetDec it will reflect these changes. This is good for dev purposes.

You **cannot** use pre-built vanilla LLVM from you system installed for example by your package manager. Unfortunately RetDec uses its own LLVM which is slightly modified and cannot work with the vanilla LLVM.
