### ISSUE TITLE
The instructions in Control Flow Graph

### ISSUE THREAD

**Issue by XX-Official** [avast/retdec#1133]
I used retdec to generate the control flow graphs with "--backend-emit-cfg", and I found the instructions in these CFGs are different with the LLVM IR. I'd like to know: What kind of language the instructions in CFGs are?
![cfg advance](https://user-images.githubusercontent.com/29937285/217421117-8b2e5cdb-0aab-4692-8391-eed2a2da56dd.png)

**Comment by PeterMatula** [comment]
Looks like it is using `llvmir2hll` internal representation. `llvmir2hll` is RetDec's backend which takes LLVM IR representation, translates it to its own repre, do some more analysis and modifications related to high-level constructs and produces high-level language (C) in the end.
