### ISSUE TITLE
How to use llvmir2hll in RetDec Release 5.0

### ISSUE THREAD

**Issue by 2994186010** [avast/retdec#1156]
Retdec-llvmir2hll is remove in RetDec Release 5.0. According to the name, retdec-llvmir2hll should reverse llvm IR into high-level language(such as C), is it right? I need to reverse llvm IR into C. And how to use llvmir2hll in RetDec Release 5.0?

**Comment by PeterMatula** [comment]
To be honest, I'm not sure `llvmir2hll` would help you much in lifting any LLVM IR into high-level language:
* I think it is (unfortunately) specifically implemented to process LLVM IR produced by RetDec. It probably will produce some output for any LLVM IR, but I'm not sure how good that would be. (It would be ideal if it was more general, but it is not.)
* I doubt it can handle the full set of stuff that can be present in LLVM IR. RetDec's frontend definitely uses only a subset, and we never really tested `llvmir2hll` on anything much different.
* RetDec uses very old LLVM, it is quite possible that if you try to lift newer LLVM IR something will break.

Have you tried the original `retdec-llvmir2hll` app before the 5.0 release? If that worked for you, great :+1: 

In any case, if you need to check if `retdec-llvmir2hll` would produce anything of benefit for you, the easiest think is to simply use the RetDec version which still has the `retdec-llvmir2hll` app. You can either download an old 4.0 pre-build release, or built it yourself from the tag. Not much, if anything, have changed in `llvmir2hll` part, so there is really no functionality you would be loosing.

Another option would be to build a custom 5.0 app that would do exactly what you want. RetDec 5.0 can be used as a library and `llvmir2hll` is an LLVM pass that could be used on its own without other parts. This would however require a bit of coding on you part. I would definitely start with 4.0 and checked it does anything of use - which I kinda doubt. If you decide to write your own app using only `llvmir2hll` pass let me know, I can give you some pointers to speed things up.
