### ISSUE TITLE
Fileinfo: takes too much memory and crashes on std::bad_alloc

### ISSUE THREAD

**Issue by PeterMatula** [avast/retdec#159]
In the following cases fileinfo reads some invalid number of entries from the analyzed binary, tries to allocate memory for all of them, eats up all the memory, and crashes on `std::bad_alloc`. If possible, we should try to avoid it.

**Comment by PeterMatula** [comment]
[73725D21DC52D28171E19BB4B6F01A92A4CE887A9FE828512E575C12DBCEC9C5](https://www.virustotal.com/en/file/73725D21DC52D28171E19BB4B6F01A92A4CE887A9FE828512E575C12DBCEC9C5/analysis/)

The problem is in `MachOFormat::dyldInfoCommand()`: ![massif](https://user-images.githubusercontent.com/20342097/35867842-1a71eb4c-0b5b-11e8-8a98-adfa2758c006.png).

There is an invalid number of exports. 

Reported to LLVM: https://bugs.llvm.org/show_bug.cgi?id=32405. If it will not get solved, try to fix it on our own.

**Comment by PeterMatula** [comment]
Asi podobny problem pri spravovani PE import directory vo vzorkach:
- [25BC72E5882F6C39EE92B7A80CF823858FE02C929FDBA0606AECD43562EA6324](https://www.virustotal.com/en/file/25BC72E5882F6C39EE92B7A80CF823858FE02C929FDBA0606AECD43562EA6324/analysis/)
- [46CE33E19087F9A50A9AE4DD7CF230391F02D97DF3A8A065A83084645E9DED23](https://www.virustotal.com/en/file/46CE33E19087F9A50A9AE4DD7CF230391F02D97DF3A8A065A83084645E9DED23/analysis/)
- `50C338A5DE623907430B6B040A8A2A2E777EB81BA7199E1E0C807FFE51874A9B`

**Comment by ladislav-zezula** [comment]
> 25BC72E5882F6C39EE92B7A80CF823858FE02C929FDBA0606AECD43562EA6324
> 46CE33E19087F9A50A9AE4DD7CF230391F02D97DF3A8A065A83084645E9DED23
> 50C338A5DE623907430B6B040A8A2A2E777EB81BA7199E1E0C807FFE51874A9B

This has already been fixed when a maximum processed import count was added.

**Comment by PeterMatula** [comment]
```
25BC72E5882F6C39EE92B7A80CF823858FE02C929FDBA0606AECD43562EA6324
46CE33E19087F9A50A9AE4DD7CF230391F02D97DF3A8A065A83084645E9DED23
50C338A5DE623907430B6B040A8A2A2E777EB81BA7199E1E0C807FFE51874A9B
```
Are indeed fixed. They were added to nightly tests.

**Comment by PeterMatula** [comment]
Also `73725D21DC52D28171E19BB4B6F01A92A4CE887A9FE828512E575C12DBCEC9C5` passes without crash.

Same as in #119, new LLVM catches the problem. It throws in Debug, and ignores in Release. Valgrind is OK. Added to nightly tests.
