### ISSUE TITLE
Suggestion from web: missing function arguments in PowerPC binary

### ISSUE THREAD

**Issue by PeterMatula** [avast/retdec#182]
[Binary](https://github.com/avast-tl/retdec/files/1703068/bin.zip) sent to us by user through https://retdec.com/.

**Reported problems:**
- Missing/bad arguments in several functions (e.g. `Max_int__Fii()` at `0xcc730`).
- Bad return types.

**Comment by PeterMatula** [comment]
Check it problem still occurs.

**Comment by xkubov** [comment]
This problem does no longer occurs. I am closing this issue.

Current output:

```c
  // Address range: 0xcc730 - 0xcc754
  int32_t Max_int__Fii(int32_t a1, int32_t a2) {
      // 0xcc730
      int32_t v1; // 0xcc730
      __asm_cror_38(v1, v1, v1);
      uint32_t v2 = __asm_mfcr(a1, a2, v1, v1, v1, v1, v1, v1); // 0xcc738
      uint32_t v3 = v2 % 2; // 0xcc73c
      return v3 - 1 & v2 | -v3 & a2;
  }                                                                                     
```
