### ISSUE TITLE
Parsing of multiple signatures from PE files

### ISSUE THREAD

**Issue by metthal** [avast/retdec#380]
We currently do not parse the signatures from PE files the same way as described [here](https://github.com/VirusTotal/yara/pull/940).

We do not support multiple `WIN_CERTIFICATE` structures and also we do not support parsing of `SPC_NESTED_SIGNATURE`. 

We already have an implementation of simple ASN1 parser so it can be used for the second case (maybe after some modifications).

**Comment by wxsBSD** [comment]
I'm happy to provide samples that have multiple WIN_CERTIFICATE structures (they are EFI images signed by both MSFT and RHAT) if you don't have any.

**Comment by metthal** [comment]
I would really appreciate that. It would help a lot. Thank you.

**Comment by wxsBSD** [comment]
Sorry, didn’t see this response until just now. Send me an email and I’ll get you a zip of them!

**Comment by PeterMatula** [comment]
Solved in https://github.com/avast/retdec/pull/902
