### ISSUE TITLE
LOG_TIMEOUT results in arbitrary termination on Windows.

### ISSUE THREAD

**Issue by Convery** [avast/retdec#444]
Simply put. LLVMIR2HLL is terminated after LOG_TIMEOUT (retdec-config.py) seconds. 
So setting the value to 10 makes the decompilation fail shortly after starting. 

Windows 7 Ultimate x64, 96GB RAM.

**Comment by s3rvac** [comment]
Hi. `LOG_TIMEOUT` is an internal setting that is used only when running `retdec-decompiler.py` with `--generate-log`, which itself is an internal parameter that should NOT be used by end users (it is not listed when running `retdec-decompiler.py --help`). Do you use this parameter? If so, simply stop using it an everything should be fine.

**Comment by Convery** [comment]
As in, the script fails after 300 on windows regardless of the actual status if it's not changed. Which, when working on binaries with a PDB attached, will always fail as it takes too long to analyse ( https://i.imgur.com/mVPiyus.png ). Sidenote; the windows versions doesn't print any output (the stages) until it terminates.

**Comment by s3rvac** [comment]
Could you please provide the following information so we can try to reproduce the issue?
1. Attach the input file that you are trying to decompile. You can ZIP it and upload here.
2. What command do you use to decompile the file?
3. Which version of RetDec do you use? E.g. release 3.2 (64b) or a custom build.
