### ISSUE TITLE
Add option to install only specific CMake targets

### ISSUE THREAD

**Issue by metthal** [avast/retdec#510]
RetDec is a large-scale project containing multiple standalone libraries and binaries. It might be useful if we were able to install only certain parts of RetDec, for example just `fileinfo` and its dependencies.

This might be achieved through `COMPONENT` attribute of `install` directives in CMake but I have never tried it myself. (https://cmake.org/cmake/help/v3.13/command/install.html)

**Comment by metthal** [comment]
I did some investigation and it doesn't look that good because of multiple reasons:

1. It is not transitive. So if I specify `COMPONENT fileinfo` to install target of `retdec-fileinfo` and use `CMAKE_INSTALL_COMPONENT=fileinfo` then only `retdec-fileinfo` is installed. Nothing else.
2. You cannot specify more than one component in `install()` directive therefore you can't for example have components for fileinfo, unpacker, ... because they share dependencies.

**Comment by PeterMatula** [comment]
Solved in #670 using a custom solution - not a very elegant one, but does everything we want it to do and all the ugliness is located in a single file `cmake/options.cmake`.
