### ISSUE TITLE
output contains garbage code from gcc

### ISSUE THREAD

**Issue by VanNostrand** [avast/retdec#514]
I built the current master branch and decompiled /bin/true to see it in action. The C output was so large that I wrote my own version to compare it. So I wrote, compiled and decompiled the following:
```C
int main() {
return 0;
}
```
The output correctly contained the main function as is but it also added several unused garbage functions and global variables (gcc-overhead?) that also prevents the generated C file to compile again, like
```C
// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t __libc_csu_fini(void);
int64_t __libc_csu_init(int64_t a1, int64_t a2, int64_t a3);
int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t deregister_tm_clones(void);
int64_t frame_dummy(void);
void function_4c0(int64_t * d);
int64_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 1456;
int64_t g2 = 1392;
int64_t g3 = 0;
int64_t g4 = 0;
int32_t g5;

// ------------------------ Functions -------------------------
//[...]
// Address range: 0x4c0 - 0x4c6
void function_4c0(int64_t * d) {
    // 0x4c0
    __cxa_finalize(d);
}
//[...]
// --------------- Dynamically Linked Functions ---------------

// void __cxa_finalize(void * d);
// void __gmon_start__(void);
// int __libc_start_main(int *(main)(int, char **, char **), int argc, char ** ubp_av, void(* init)(void), void(* fini)(void), void(* rtld_fini)(void), void(* stack_end));

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (8.2.0)
// Detected functions: 11
// Decompilation date: 2019-03-06 13:43:29
```
It would be nice to have an option that removes all unused functions from the generated output. While this is not suitable for libraries or such, it is what I expect from decompiling a main program (at least, easy code like that should be compilable again).

Nice thing though, it works with clang as expected. This is the output of a decompiled clang-generated code:
```C
//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------------ Functions -------------------------

// Address range: 0x400470 - 0x40047f
int main(int argc, char ** argv) {
    // 0x400470
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (8.2.0)
// Detected functions: 1
// Decompilation date: 2019-03-06 14:01:52
```
It seems to detect clang as gcc though. My tested clang version was
> clang version 7.0.1 (tags/RELEASE_701/final)
> Target: x86_64-pc-linux-gnu
> Thread model: posix

But back to the first issue: First I thought, clang might strip the binary, but after stripping the gcc generated binary, the output was pretty unreadable (it did not even have a main function anymore; though it had several functions that just returned 0 or a global var that was 0 or an unassigned int that could be 0 and it had a function that returned on of these functions...)

**Comment by s3rvac** [comment]
Hi. You have correctly identified the generated code to come from GCC. The code contains startup and exit routines that are used to e.g. initialize and de-initialize the standard C library.

Although RetDec supports removal of statically linked code coming from compilers and standard libraries, there is a huge variety of different compilers, compiler versions, and standard libraries, that we are unable to cover them all. Instead, we encourage each user to generate statically linked code signatures tailored for their environment by following [these steps](https://github.com/avast/retdec/wiki/Removing-Statically-Linked-Code). Please, try it and let us know if you have any questions towards this.
