### ISSUE TITLE
How to install and run RetDec in Windows?

### ISSUE THREAD

**Issue by MBilalQureshi** [avast/retdec#547]
I am trying to install retdec decompiler by avast, the issue is i am new in this field and i can't install it properly as described in this link 
**https://github.com/avast-tl/retdec
Windows 

Either download and unpack a pre-built package, or build and install the decompiler by yourself (the process is described below).

Install Microsoft Visual C++ Redistributable for Visual Studio 2015.

Install the following programs:

Python (version >= 3.4)
UPX (Optional: if you want to use UPX unpacker in the preprocessing stage)
Graphviz (Optional: if you want to generate call or control flow graphs)
Now, you are all set to run the decompiler. To decompile a binary file named test.exe, run the following command (ensure that python runs Python 3; as an alternative, you can try py -3)

python $RETDEC_INSTALL_DIR/bin/retdec-decompiler.py test.exe
For more information, run retdec-decompiler.py with --help.** 

1. Where do i put unpack folder?
2. will i run commands like $RETDEC_INSTALL_DIR/bin/retdec-decompiler.py test.exe in cmd?
3. What is this $ mean before RETDEC_INSTALL_DIR and will this  RETDEC_INSTALL_DIR mean the actual path where retdec is.
4. Do i need to run this in python cmd after py-3 ?
5. what if i had another file to be decompiled just like test.exe, where do i put it.

Again sorry but i need guidance?
**One thing more can retdec decompile .DLL files written in C ?**

**Comment by silverbacknet** [comment]
Download from https://github.com/avast-tl/retdec/releases and unzip to a folder. It's that simple, don't read about rebuilding it yourself if you aren't familiar with the process.

You will have to use command line to decompile your favorite DLL (yes, DLL files written in C are the target audience); if you aren't familiar with that, then it's probably time to get used to it.

**Comment by MBilalQureshi** [comment]
![retdec](https://user-images.githubusercontent.com/29452447/56205416-2af15a80-6063-11e9-9513-6c1e98b1d60a.png)

@silverbacknet i am getting this error, after the line i had written in cmd...am i doing it wrong?

**Comment by s3rvac** [comment]
@MBilalQureshi The `$RETDEC_INSTALL_DIR` part of the path is user specific and has to be updated to match your system. For example, if you have unzipped the archive into `C:\` and you are currently in `C:`, run just
```
python retdec/bin/retdec-decompiler.py
```

**Comment by MBilalQureshi** [comment]
@s3rvac ok i have understand this part you have mentioned above but what i am getting is this
![image](https://user-images.githubusercontent.com/29452447/56206314-83295c00-6065-11e9-9844-f6df93bf196e.png)
can you help me this ? why am i getting this in cmd, even python is installed.

**Comment by s3rvac** [comment]
Do you have Python 3 installed in your system? You can also try running
```
py -3 retdec/bin/retdec-decompiler.py
```
(Note that there is only a single `-` in the command, i.e. use `-3`, NOT `--3`.)

**Comment by MBilalQureshi** [comment]
@s3rvac OK, this worked **py -3 retdec/bin/retdec-decompiler.py** Thank you
now where do i put a file like for example test.exe or test.dll to get decompiled code
![image](https://user-images.githubusercontent.com/29452447/56208028-96d6c180-6069-11e9-81bc-856407217deb.png)

**Comment by s3rvac** [comment]
Put it after the command, e.g.
```
py -3 retdec/bin/retdec-decompiler.py test.exe
```
The output C code will be then in file `test.exe.c`.

**Comment by s3rvac** [comment]
Of course, the file has to be in the current folder. If not, you will have to specify a full path to the file.

**Comment by MBilalQureshi** [comment]
@s3rvac ok i put the file in C directory but it is giveing me this can you help? i don't know what is causing this.
![image](https://user-images.githubusercontent.com/29452447/56211454-61ce6d00-6071-11e9-8824-16325e4fce50.png)

**Comment by s3rvac** [comment]
As the error message says, you do not have permissions to create the file in `C:\` (you have probably some protection from writing files directly to `C:\`). I suggest moving both the `retdec` folder and the input file to a different folder (e.g. `C:\decompiler`) and run the command from there.

**Comment by MBilalQureshi** [comment]
@s3rvac ok thanks that worked, one last thing how to use UPX along retdec ? i can use this on cmd C:\UPX>upx.exe but that just opened upx options for compression and decompression. what should i do in this case?

**Comment by s3rvac** [comment]
If you have UPX installed and available in PATH (meaning that you can run `upx` from anywhere), RetDec will automatically detect it and use it. So, apart from properly installing UPX, there is nothing you need to do.

**Comment by s3rvac** [comment]
Closing as resolved. If you have further questions, please re-open (if the question is related to this issue) or open a new issue.

**Comment by nadiab123** [comment]
Hello to All,
I want to to install and run RetDec in Windows 10 64bit , but i'm given me a message error as following:

C:\>py -3 RetDec/bin/retdec-archive-decompiler.py GesCleMM.exe
Error: Input GesCleMM.exe is not a valid file.

what should i do in this case????

**Comment by silverbacknet** [comment]
> Error: Input GesCleMM.exe is not a valid file.

That error means the file isn't there, so, check your typing and paths? The very first thing you should do? And then open a NEW issue instead of piggy-backing on this.

**Comment by nadiab123** [comment]
hello,

i 'm checked the type and the path of the file but i'm not succed to run it.

![image](https://github.com/avast/retdec/assets/138603059/96198663-5a91-4ea7-ab31-e67de435db47)

**Comment by nadiab123** [comment]
hello,

i 'm checked the type and the path of the file but i'm not succed to run it.

[image: image]
<https://user-images.githubusercontent.com/138603059/251191872-96198663-5a91-4ea7-ab31-e67de435db47.png>

Le mar. 4 juil. 2023 à 21:20, Emily Bowman ***@***.***> a
écrit :
