### ISSUE TITLE
What Should One Do (Manually) To The Output of Retdec To Make It Compilable?

### ISSUE THREAD

**Issue by humanitiesclinic** [avast/retdec#563]
Related to #529, #562, #45, but not exactly a duplicate. Also, this is still relevant even when Retdec’s aim is not so much to produce code that can be decompiled as much as to produce code analysable by a human. It is still relevant to someone just trying to analyse the output of Retdec without re-compiling it.

Given the output files of Retdec, what should one do (manually) to make it compilable?

Eg:
(1) Is the output standard C, or just C-like?
(2) If it’s standard C, why is still not recompilable? Because of unresolvable references etc.

There’s some discussion in #45, but there’s no step-by-step instruction or tutorial (with samples etc.) like what should one change in the output files, and which libraries must one link to again. Wish there’s a tutorial or some sort. This will make it very clear what in the output files of Retdec are missing and different from compilable code, *and one needs to know this to understand the code even if one doesn’t wish to recompile it per se*.

**Comment by humanitiesclinic** [comment]
Any suggestions?

**Comment by s3rvac** [comment]
Hi. I will try to provide answers to your questions. @PeterMatula can supply additional information in case I miss something.

As for question number (1), we strive to produce output that conforms to [ISO C99](https://en.wikipedia.org/wiki/C99). So yes, the output should be C, not just C-like. However, things are not that simple, see below.

As for question number (2), there are generally two reasons why the generated C code is not re-compilable:
1. Things that **can** be solved by fixing/improving RetDec.
    * Adding support for unsupported instructions. When RetDec encounters an instruction that it does not know how to lift to a higher-level representation, it emits an `__asm_XYZ` function call, where `XYZ` is the name of the instruction. Example:
        ```cpp
        int128_t d = __asm_addsd(__asm_divsd(a, b), c);
        ```
        This can be fixed by adding support for these instructions. However, this may not always be possible/desirable, as instructions may be unrepresentable (or hard to represent) in a high-level form. Such instructions may include standard architecture extensions (MMX, SSE, etc.) as well as platform-dependent extensions (e.g. instructions for a specific device, such as PlayStation).
    * Fixing reconstruction of types. Sometimes, it may happen that RetDec reconstructs incorrect types, which results in compiler errors. Example:
        ```cpp
        struct X {
            int i;
        };

        void foo(struct X x);

        foo(1);
        ```
    * Fixing reconstruction of functions. Sometimes, it may happen that RetDec emits incorrect function bodies, such as with missing `goto` labels, duplicate `goto` labels, or use of undeclared variables. Example:
        ```cpp
        void foo() {
            // ...
            generated_label:
                // ...
            // ...
                generated_label:
                // ...
            // ...
        }
        ```
2. Things that **cannot** be solved by fixing/improving RetDec.
    * Having signatures for detecting all statically linked code that should not be decompiled. Such code includes compiler runtime (before `main()`) and functions from the standard library (e.g. `printf()`). When re-compiling the code, these functions are inserted into the binary file automatically by the compiler, and if there are decompiled, the compiler will refuse to compile the code. The biggest issue with this point is that there is a huge number of different compilers and standard libraries and RetDec cannot cover them all (this would make it really huge and slow). Thus, users are encouraged to [generate such signatures by themselves](https://github.com/avast/retdec/wiki/Removing-Statically-Linked-Code).
    * Unresolved references. The decompiled code may contain references to functions that are not present in the code. In such cases, you have to provide them by yourself when compiling (to provide their declaration) and linking (to provide their definition). RetDec in general has no way of knowing which header files and libraries should be used when compiling and linking the decompiled file.

**Comment by s3rvac** [comment]
As for this point:

> There’s some discussion in #45, but there’s no step-by-step instruction or tutorial (with samples etc.) like what should one change in the output files, and which libraries must one link to again.

I am afraid there won't be any such tutorial as there is a huge variety of different errors that could go wrong. However, I have been wrong before, so maybe someone actually writes it (it won't be us, though). The best instructions we can give you at the moment are:
1. Try to compile the generated C source code.
2. Take a look at the first error, understand what it says, and fix it in the source code (or in the compilation command, e.g. by providing libraries containing unresolved dependencies).
3. Repeat steps 1 and 2 until the code compiles without any errors.

We are aware that this might not be what you are looking for, but it is the best we can give you at the moment.

**Comment by humanitiesclinic** [comment]
Your answer's very helpful so far @s3rvac. Even though as you said "this might not be what [I am] looking for", it's a good start, and at least I can use it as a starting point. thank you very much! I will read the publications to fill in the gaps, and if there's anything else I will post again.

**Comment by PeterMatula** [comment]
My two cents:
* Don't try to re-compile RetDec's output.
* Don't try to manually modify and re-compile RetDec's output.

Currently, we are not producing output of sufficient quality to gain anything from compiling it. I doubt this will get better in the future. Decompilation is hard and the way we do things, it is pretty much impossible to decompile a binary of some complexity into something that you could re-compile (even with manual modifications) and expect to work. This project is focused on manual analysis of the output and it is likely we will add more features that goes in this direction in the future (e.g. calling conventions, x86 FPU/SSE intrinsics).
