### ISSUE TITLE
Is it possible to guess the amount of memory RetDec will need for decompilation?

### ISSUE THREAD

**Issue by SamDecrock** [avast/retdec#572]
Is there a way to guess the amount of memory retdec is going to need for decompilation?

I'm thinking of creating a web service to automate decompilation. The idea is to spin up a cloud instance with the right amount of memory, do decompilation and shut it down once decompilation is done.

To optimize costs (= decide which cloud instance to spin up) it would be good if I could know how much memory the process is going to take up.

Sam

**Comment by s3rvac** [comment]
Hi. I am afraid that there is no simple relation between static properties of the input file and the amount of memory RetDec will need to decompile it. A rule of thumb may be _the bigger the file, the more memory RetDec may need_, but this is generally an oversimplification. The amount of memory depends on many factors, including the number of instructions in the file, whether RetDec is able to correctly decode the instructions, detection of statically linked code, and decompilation parameters (e.g. selective decompilation may require less memory than full decompilation).

One of our long-term goals is to reduce memory requirements of RetDec (#13), but this is going to be a long run.

**Comment by SamDecrock** [comment]
Ok, I figured the _the bigger the file, the more memory RetDec may need_ was going to be my only option.

Another question, is there a way to continue decompilation where it left it of? That way I can start on a normal machine but continue on a machine with more memory in case decompilation stops due to memory shortage.
