### ISSUE TITLE
Can I continue decompilation on a different machine after failure?

### ISSUE THREAD

**Issue by SamDecrock** [avast/retdec#574]
Is there a way to continue decompilation where it left it of? That way I can start on a normal machine but continue on a machine with more memory in case decompilation stops due to memory shortage.

**Comment by s3rvac** [comment]
Hi. Good question. The answer is no and yes, depending on how you look at it :-). I will give you a description of the current status and you can then decide by yourself.

_No:_ There is no built-in decompilation parameter that would allow you grab the intermediate outputs, copy them somewhere else, and continue the decompilation from there. Also, the decompilation process is done via a chain of several tools, each taking input from the previous tool and generating output for the next tool, so when a tool abruptly ends, it does not stores its output anywhere (it is lost).

_Yes:_ As I have written above, each decompilation is a series of calls to various tools (e.g. `retdec-fileinfo`, `retdec-bin2llvmir`, `retdec-llvmir2hll`). For the sake of explanation, let's say that a decompilation is done by calling five tools, `A` through `E`. If tool `C` fails, you can grab the outputs produced by `B`, parse the output of `retdec-decompiler.py` to get the command that was used to run `C`, and run that command. However, you would then have to craft arguments for tools `D` and `E`, which is tricky as their arguments may depend on both decompilation parameters and outputs from previously run tools.

If you really need this, I suggest creating a custom version of `retdec-decompiler.py` (and possibly of other scripts) that is tailored to your needs. If you have specific use cases (i.e. only decompilation of PE binaries with default arguments), the script could be pretty small. However, it will require you to understand how the tools are interconnected and how the decompilation process works.
