### ISSUE TITLE
Mach-O arm64 support missing

### ISSUE THREAD

**Issue by Masrepus** [avast/retdec#639]
As we just discussed at r2con, here is my issue:

I need to lift iOS apps to llvm. For this, I would like to try retdec, by using the `retdec-decompiler.py --stop-after bin2llvmir` command. Unfortunately, iOS apps are arm64 Mach-O files, and this combination of file format and architecture is currently not supported by retdec.

You told me, that arm64 support is actually present (but probably only for ELFs), as is Mach-O (only for 32bit).

If you currently do not have the time to work on this, I am happy to work on a pull request, as long as you can provide me with some infos on where to start.

**Comment by metthal** [comment]
Thanks for filing the issue. Could you also provide us with some sample files so we can try and confirm that it is indeed not working? We would also have something to test retdec against because I don't think we have any iOS apps. You can send them to marek.milkovic@avast.com if you don't want to share them publicly.

**Comment by Masrepus** [comment]
Ah right, here you have the one I tried before. At the moment I don't have access to more binaries, but I can send you some more later, if you need.
[CrackMe.zip](https://github.com/avast/retdec/files/3584711/CrackMe.zip)

**Comment by xkubov** [comment]
Hi, tried to decompile the file that you have provided and decompilation was successful. 
I've tried to decompile provided file on current master (`63f03e79`) and got the following output:
[CrackMe-out-63f03e79.zip](https://github.com/avast/retdec/files/3590810/CrackMe-out-63f03e79.zip)

Is it possible that you have used some old version of RetDec?

**Comment by Masrepus** [comment]
Ah I used v3.3 from the releases page. Didn't see that there have been >300 commits since then...
Anyway thank you for your help!
