### ISSUE TITLE
Functions returning floating point values on MIPS return integer register

### ISSUE THREAD

**Issue by PeterMatula** [avast/retdec#656]
Due to #652, I had to disable 2 MIPS regression tests. Once again, this was pre-existing problem that only got uncovered by the register localization.

Tests:
```
integration.float-operations.Test_2015 (float-operations.mips.pspgcc-4.3.5.O0.g.elf)
integration.float-operations.Test_2017 (float-operations.mips.gcc.O0.g.elf)
```

It looks like we return an integer register, even when we know (from debug info) that the function returns floating point.

In `float-operations.mips.pspgcc-4.3.5.O0.g.elf`:
```llvm
; 0x89003e4
  store volatile i64 143655908, i64* @_asm_program_counter
  %85 = load i32, i32* @v0
  %86 = bitcast i32 %85 to float
  ret float %86
```

It worked before, because the computed values got stored to global variable representing register in one function, and got read in another function:
```c
float32_t op1(int32_t a, int32_t b) {
    // 0x8900368
    printf("mul by %f\n", 3.789);
    g1 = 3.789 * (float64_t)(float32_t)b + (float64_t)(float32_t)a;
    return (int32_t)&g2;
}
```
But when registers get localized, the store gets optimized away:
```c
float32_t op1(int32_t a, int32_t b) {
    // 0x8900368
    printf("mul by %f\n", 3.789);
    return (int32_t)&g1;
}
```
Everything would work, if function read return value from `$f0` instead of `$v0`.

According to page `3-21` in this it should: http://math-atlas.sourceforge.net/devel/assembly/mipsabi32.pdf

Can you please look at it with priority? Maybe it will be an easy fix. You don't need to work with `reg-localization` branch where #652 is implemented. It is possible to fix it in `master`.

**Comment by xkubov** [comment]
This issue is solved by 61af12f. I am closing it now. 

Tests were reenabled: https://github.com/avast/retdec-regression-tests/commit/f53449cdd61a400d8f0ffb4b3e77fd43fc4fae54
