### ISSUE TITLE
Can't download build

### ISSUE THREAD

**Issue by trsh** [avast/retdec#675]
retdec-v3.3-windows-64b.zip downloads with speed like 12kb/s and then dies in middle. My internet connection is not the best, but this is just ... to crappy

**Comment by s3rvac** [comment]
GitHub hosts releases on AWS and AFAIK there is nothing we could do on the RetDec's side to improve this. I have just tried downloading that archive and the speed was around 15 MB/s, but I have also seen very slow speeds in the past. Thus, I am closing the issue.

**Comment by trsh** [comment]
:/

**Comment by trsh** [comment]
@s3rvac can you do a favor and upload it on https://wetransfer.com/ and share the link. Like on time thing. I really need this.

**Comment by s3rvac** [comment]
Anyway, if you try to google ["github download slow speed"](https://www.google.com/search?q=github+download+slow+speed), you will get a lot of similar reports.

**Comment by s3rvac** [comment]
I have sent you the link to your email address. It will be available only for a week.

**Comment by trsh** [comment]
Tnx
