### ISSUE TITLE
'upx' not avaliable: nothing to do

### ISSUE THREAD

**Issue by pechenzz** [avast/retdec#688]
This error doesn't let me decompile my exe file! btw im using retdec-decompiler.py. And im opening it using python3 on windows 7 laptop.

**Comment by s3rvac** [comment]
Hi. Do you have [UPX](https://upx.github.io/) installed in your system? It is required by RetDec, see the [instructions](https://github.com/avast/retdec#windows).

**Comment by s3rvac** [comment]
Anyway, can you please provide a complete output from the decompilation? The unpacking step is only optional and the decompilation should not fail just because you do not have UPX in your system.

**Comment by pechenzz** [comment]
![Снимок](https://user-images.githubusercontent.com/59606818/71895352-e6ae6900-3161-11ea-947c-8f32f349c2a5.PNG)
Im actually dont have UPX in my system. Also it gives longer result when i use dnd to choose a file to decompile.

**Comment by s3rvac** [comment]
You have originally written that you have used `retdec-decompiler.py`, but in the screenshot above, you have used `retdec-unpacker.py`, which is just the unpacking part of `retdec-decompiler.py`. Please, ensure that you use `retdec-decompiler.py`.

**Comment by pechenzz** [comment]
oh, my apologies.

**Comment by s3rvac** [comment]
No worries.

**Comment by pechenzz** [comment]
uh, wat do i do? Its stuck.
![Снимок](https://user-images.githubusercontent.com/59606818/71895836-2d509300-3163-11ea-99d2-2ad43b8475eb.PNG)
![Снимок1](https://user-images.githubusercontent.com/59606818/71895838-2d509300-3163-11ea-8cb5-24b4ed34f0ce.PNG)

**Comment by s3rvac** [comment]
If you read the output carefully, there is the following warning:
```
Detected CIL/.NET bytecode, which cannot be decompiled by our machine-code decompiler.
The decompilation result may be inaccurate.
```
It is decompiling byte code, so you won't receive any useful results. RetDec is a machine-code decompiler and does not work correctly on bytecode.

**Comment by pechenzz** [comment]
Oh, well, my apologies again, need to search for other decompiler, but maybe this decompiler will help me in some other way.
