### ISSUE TITLE
я просто сообщил о том что ваш говнодекомпилятор нефига даже не пытается декомпилировать :D

### ISSUE THREAD

**Issue by d-karaulov** [avast/retdec#698]
@s3rvac я просто сообщил о том что ваш ссаный говнодекомпилятор нефига даже не пытается декомпилировать :D
https://github.com/avast/retdec/issues/697
можешь не исправлять мне как-то похер)

**Comment by xkubov** [comment]
You really do enjoy spamming, don't you?
