### ISSUE TITLE
Small errors ?

### ISSUE THREAD

**Issue by megacoderencoderdecoder** [avast/retdec#704]
https://github.com/avast/retdec/blob/cb28048f8bd9d358ece8217b2e1c83e25b93b2e8/src/llvmir2hll/semantics/semantics/gcc_general_semantics/get_symbolic_names_for_param.cpp#L360
and
https://github.com/avast/retdec/blob/cb28048f8bd9d358ece8217b2e1c83e25b93b2e8/src/llvmir2hll/semantics/semantics/gcc_general_semantics/get_symbolic_names_for_param.cpp#L361

--------
https://github.com/avast/retdec/blob/cb28048f8bd9d358ece8217b2e1c83e25b93b2e8/src/llvmir2hll/semantics/semantics/gcc_general_semantics/get_symbolic_names_for_param.cpp#L1385
and
https://github.com/avast/retdec/blob/cb28048f8bd9d358ece8217b2e1c83e25b93b2e8/src/llvmir2hll/semantics/semantics/gcc_general_semantics/get_symbolic_names_for_param.cpp#L1386

--------
https://github.com/avast/retdec/blob/cb28048f8bd9d358ece8217b2e1c83e25b93b2e8/src/llvmir2hll/semantics/semantics/win_api_semantics/get_symbolic_names_for_param.cpp#L70
and
https://github.com/avast/retdec/blob/cb28048f8bd9d358ece8217b2e1c83e25b93b2e8/src/llvmir2hll/semantics/semantics/win_api_semantics/get_symbolic_names_for_param.cpp#L71
--------
https://github.com/avast/retdec/blob/cb28048f8bd9d358ece8217b2e1c83e25b93b2e8/src/pat2yara/logic.cpp#L102
		**if (!lowUnit->isNibble() || !lowUnit->isNibble()) {**
--------
https://github.com/avast/retdec/blob/cb28048f8bd9d358ece8217b2e1c83e25b93b2e8/src/yaracpp/yara_detector/yara_detector.cpp#L353
and
https://github.com/avast/retdec/blob/cb28048f8bd9d358ece8217b2e1c83e25b93b2e8/src/yaracpp/yara_detector/yara_detector.cpp#L360
**rules and rules**

**Comment by s3rvac** [comment]
Hi. I am not sure why you have closed the issue. Has everything from this issue been reported in #703?

**Comment by megacoderencoderdecoder** [comment]
Yes i move message to #703
