### ISSUE TITLE
Memory leak in DeadLocalAssignOptimizer

### ISSUE THREAD

**Issue by megacoderencoderdecoder** [avast/retdec#705]
I tested Retdec with one executable (Windows x64 executable, binary size 45MB) and got a terrible result.

**Comment by megacoderencoderdecoder** [comment]
![2020-02-11-07-41-40](https://user-images.githubusercontent.com/60728708/74211916-083fca80-4ca3-11ea-86fc-12227928fe94.gif)

**Comment by megacoderencoderdecoder** [comment]
![3LM8sr9 1](https://user-images.githubusercontent.com/60728708/74211546-610e6380-4ca1-11ea-966a-4682155b76cb.png)

** DeadLocalAssignOptimizer uses 622GB of RAM! **

**Comment by megacoderencoderdecoder** [comment]
![E0CmUoA 1](https://user-images.githubusercontent.com/60728708/74213786-d717c800-4cab-11ea-9d52-6178e93303e9.png)

**Comment by s3rvac** [comment]
Hi. Could you please elaborate on why do you think this is a memory leak? I see no such indication in the issue description or comments.

Anyway, you won't have much luck trying to decompile a 45 MB binary file all at once. I suggest using _selective decompilation_ instead (see e.g. [this comment](https://github.com/avast/retdec/issues/565#issuecomment-488209435)). For more information about RetDec's memory issue, please see issues labeled by [T-memory](https://github.com/avast/retdec/issues?utf8=%E2%9C%93&q=label%3AT-memory+).

**Comment by megacoderencoderdecoder** [comment]
**Terminated on 1TB of RAM :(**

**Comment by s3rvac** [comment]
Please, try selective decompilation as suggested by me above. You won't be able to decompile the file all at once.

**Comment by s3rvac** [comment]
I am closing the issue as there are many other issues for too-high-memory-requirements for RetDec.
