### ISSUE TITLE
Incorrect decompilation output (various calling conventions)

### ISSUE THREAD

**Issue by megacoderencoderdecoder** [avast/retdec#707]
https://pastebin.com/Hr3aybPk
```
#include <Windows.h>
#include <string>

int __cdecl Test1_part4(int a1, int a2, int a3)
{
	return '0' + a1 + a2 + a3;
}

int __stdcall Test1_part3(int a1, int a2, int a3)
{
	return Test1_part4(a1, a2, a3);
}

int __cdecl Test1_part2(int a1, int a2, int a3)
{
	return Test1_part3(a1, a2, a3);
}

int __vectorcall Test1_part1(int a1, int a2, int a3)
{
	return Test1_part2(a1, a2, a3);
}

int __fastcall Test1(int a1, int a2, int a3)
{
	return Test1_part1(a1, a2, a3);
}

void PrintInt(int a1)
{
	char tmp[2];
	tmp[0] = a1;
	tmp[1] = '\0';
	MessageBoxA(0, tmp, tmp, 0);
}

int main()
{
	int retval = Test1(1, 2, 3);
	PrintInt(retval);
	system("pause");
}
```

**Compiled binary**: (x64 with Visual Studio 2019) [TestRetdec.zip](https://github.com/avast/retdec/files/4185867/TestRetdec.zip)
**Result** : https://pastebin.com/d3bRvPHL
**Problem**: I can't found line **system("pause")** in retdec output! And Test1 function calling. (And other too)
And I can't found function 'PrintInt' in code...

**Comment by megacoderencoderdecoder** [comment]
Snowman decompilation output : https://pastebin.com/VrAVVbgS

```
uint32_t fun_140011190(int64_t rcx, int64_t rdx, int64_t r8) {
    int32_t ecx4;
    int32_t eax5;

    ecx4 = 66;
    while (ecx4) {
        --ecx4;
    }
    fun_140011082(0x140021026);
    eax5 = fun_140011136(1, 2, 3);
    fun_1400112b7(eax5, 2, 3);
    system("pause", 2, 3);
    return 0;
}

I see   **system("pause", 2, 3);**, and all other functions.
```
**fun_140011136 == Test1
fun_14001128a == Test1_part1
fun_14001129e == Test1_part2
fun_14001127b == Test1_part3
fun_140011352 == Test1_part4
**

**Comment by megacoderencoderdecoder** [comment]
In retdec, main func possible:

```
int64_t function_140011ad0(int64_t a1) {
    // 0x140011ad0
    int64_t v1; // bp-280, 0x140011ad0
    __asm_rep_stosd_memset((char *)&v1, -0x33333334, 66);
    bool v2; // 0x140011ad0
    int64_t command = (v2 ? -264 : 264) + (int64_t)&v1; // 0x140011aec
    function_140011082(command);
    function_140011136();
    function_1400112b7();
    system((char *)command);
    return 0;
}
```
But i can't see Test1 calling, and system("pause")

**Comment by megacoderencoderdecoder** [comment]
And some other problems in decompiling output: 

```
char* g5[5] = {
    "Stack pointer corruption",
    "Cast to smaller type causing loss of data",
    "Stack memory corruption",
    "Local variable used before initialization",
    "Stack around _alloca corrupted"
}; // 0x14001a358
```
`g5` is `const char *` (error E0144)

```
int32_t g49;
// Address range: 0x140011005 - 0x14001100a
int64_t function_140011005(void) {
    // 0x140011005
    _cexit();
    return &g49;
}
```
function return int32_t * g49, but need int64_t
```
// Address range: 0x140011032 - 0x140011037
int64_t function_140011032(void) {
    // 0x140011032
    int64_t dwExceptionCode; // 0x140011032
    int64_t dwExceptionFlags; // 0x140011032
    int64_t nNumberOfArguments; // 0x140011032
    int64_t lpArguments; // 0x140011032
    RaiseException((int32_t)dwExceptionCode, (int32_t)dwExceptionFlags, (int32_t)nNumberOfArguments, (int32_t*)lpArguments);
    return g49;
}
```
RaiseException - last argument is **CONST ULONG_PTR* **, not int32_t

```
int64_t function_1400111f4(void) {
    // 0x1400111f4
    int64_t hWnd; // 0x1400111f4
    int64_t lpText; // 0x1400111f4
    int64_t lpCaption; // 0x1400111f4
    int64_t uType; // 0x1400111f4
    return MessageBoxA((int64_t*)hWnd, (char*)lpText, (char*)lpCaption, (int32_t)uType);
}

```
MessageBoxA - first argument is HWND, but not int64_t
```

int64_t function_140011750(int64_t a1, int64_t lpText, int64_t a3, int64_t a4, int64_t a5, int64_t a6, int64_t a7) {
    // 0x140011750
    int64_t v1; // bp-280, 0x140011750
    int64_t v2 = &v1; // 0x14001175d
    int64_t v3; // bp-312, 0x140011750
   // __asm_rep_stosd_memset((char*)&v3, -0x33333334, 74);
    bool v4; // 0x140011750
    int64_t hWnd = (v4 ? -296 : 296) + (int64_t)&v3; // 0x14001176f
    function_140011082(hWnd);
    *(char*)(v2 | 4) = (char)a4;
    *(char*)(v2 | 5) = 0;
    int64_t lpCaption; // bp-276, 0x140011750
    MessageBoxA((int64_t*)hWnd, (char*)lpText, (char*)&lpCaption, 0);
    function_140011348();
    return function_1400110d2();
}
```
v2 = &v1 problem
MessageBoxA - first argument is HWND, but not int64_t


etc

**Comment by xkubov** [comment]
This issue is partially solved by 6cc12004. The parameters are passed as you would expect on x64 Microsoft architecture.

When it comes to the bad detection of the real types of local/global variables this should come as a separate issue. We are aware of the problem of detecting/providing correct datatypes. This, however, is going to be solved for example by allowing a user of RetDec to specify data types. Currently, we are working on providing info from 3rd party "GUI" applications. This option is only in it's beginning and will be further developed in the future (see for example our [r2plugin](https://github.com/avast/retdec-r2plugin) or [idaplugin](https://github.com/avast/retdec-idaplugin)).

If you continue to have more issues feel free to open a new one.

**Comment by megacoderencoderdecoder** [comment]
@xkubov possible for detect calling conventions need just check function disassembly ???

For example (x86 microsoft)

funciton_start
if first mov xxx,**ecx**  then it can be thiscall fastcall or vectorcall(like fastcall)
...
**ret 4** - one additional parameter like stdcall
function end

funciton_start
if first mov xxx,**ecx** and/or mov xxx,**edx** then it can be only **fastcall** or **vectorcall**(like fastcall)
...
**ret 8** - two additional parameters like stdcall
function end


and etc...

**Comment by xkubov** [comment]
Yes, this can be done theoretically. But in the long run, it had much worse results than applying the default convention. RetDec is capable of applying different calling conventions on the function and we did have turned the heuristic on but as I said, the results were not good. We have chosen the option that the user should tell what convention the function has as it does have better results. Right now you can do so by modifying the config file RetDec give on the output (`config.json`) or through some kind of plugin of third part application (IDA plugin, r2plugin).
