### ISSUE TITLE
Memory leak list by Leak Detector in retdec-llvmir2hll

### ISSUE THREAD

**Issue by megacoderencoderdecoder** [avast/retdec#709]
**Sorry, but Retdec is one very big memory leak??)))))**

Memory leak list in **retdec-llvmir2hll.exe** from big to small

https://github.com/avast/retdec/blob/4e1c18cdc570d27cef2c5f6ecc5ee882f1120be9/src/llvmir2hll/ir/var_def_stmt.cpp#L136

https://github.com/avast/retdec/blob/4e1c18cdc570d27cef2c5f6ecc5ee882f1120be9/src/llvmir2hll/ir/variable.cpp#L184

https://github.com/avast/retdec/blob/4e1c18cdc570d27cef2c5f6ecc5ee882f1120be9/src/llvmir2hll/graphs/cfg/cfg_builders/non_recursive_cfg_builder.cpp#L623

https://github.com/avast/retdec/blob/4e1c18cdc570d27cef2c5f6ecc5ee882f1120be9/src/llvmir2hll/graphs/cfg/cfg_builders/non_recursive_cfg_builder.cpp#L172

https://github.com/avast/retdec/blob/4e1c18cdc570d27cef2c5f6ecc5ee882f1120be9/src/llvmir2hll/graphs/cfg/cfg_builders/non_recursive_cfg_builder.cpp#L190

https://github.com/avast/retdec/blob/4e1c18cdc570d27cef2c5f6ecc5ee882f1120be9/src/llvmir2hll/graphs/cfg/cfg.cpp#L732

https://github.com/avast/retdec/blob/4e1c18cdc570d27cef2c5f6ecc5ee882f1120be9/src/llvmir2hll/ir/return_stmt.cpp#L102

https://github.com/avast/retdec/blob/4e1c18cdc570d27cef2c5f6ecc5ee882f1120be9/src/llvmir2hll/ir/assign_stmt.cpp#L118

https://github.com/avast/retdec/blob/4e1c18cdc570d27cef2c5f6ecc5ee882f1120be9/src/llvmir2hll/ir/call_expr.cpp#L235

https://github.com/avast/retdec/blob/4e1c18cdc570d27cef2c5f6ecc5ee882f1120be9/src/llvmir2hll/ir/function.cpp#L457

Sorry but this only first leaks (70% of all leak memory) from very very big list of memory leaks :( I can't wrote all because this is bigger than 10000 results :(

**Comment by xkubov** [comment]
Thank you for analyzation of the llvmir2hll code. Well yes, the delete operator is not called afterward in provided examples, but as you can see these created pointers are managed by the ShPtr object - [shared_pointer object])

From documentation:

> Objects of shared_ptr types have the ability of taking ownership of a pointer and share that ownership:  once they take ownership, the group of owners of a pointer becomes responsible for its deletion when the last one of them releases that ownership.

In RetDec the ShPtr object is defined in `include/retdec/llvmir2hll/support/smart_ptr.h` as:
```
using ShPtr = std::shared_ptr<T>;
```

As all of these issues are related to calling the new operator and assigning the pointer to the instance of shared_pointer class which deals with deletion of the object I am closing this issue.

**Comment by megacoderencoderdecoder** [comment]
@xkubov sorry but i can't understand your answer

Leak detector found memory leaks (very big count, ~10k in only in retdec-llvmir2hll)
Memory not cleanup after process end.

**Comment by xkubov** [comment]
Well, from the examples you gave us it can be seen, that the shared_pointer is used with LLVM objects. If I am not wrong, those objects do store only the raw pointer, so the counter of the shared_pointer is not incremented (no circular dependencies). From my view, it is not possible for those objects to leak, but I might be wrong. What do you think @s3rvac ?

**Comment by megacoderencoderdecoder** [comment]
@xkubov I download Deleaker with 14-day trial. 

After process all this memory is not cleanup, and stay allocated in memory. Deleaker see this memory and shown allocation address in list?

**Comment by silverbacknet** [comment]
In this case, there are multiple possible interpretations: That there are retdec leaks resulting in unnecessary continuous allocations, or that Deleaker is detecting non-leaks as leaks because it doesn't understand the type of pointer, or that a leak doesn't matter because they're needed right up until the process shuts down.

**Comment by s3rvac** [comment]
There may be memory leaks in our tools, and are detectable e.g. by using [`valgrind`](https://valgrind.org/) (an open-source tool for detecting memory errors). However, reporting only some of them (moreover detected by a proprietary detector) makes little sense.  We will have to analyze them when we get to solving memory issues in general.

So, thank you for the report, but the reported issue is useless for us. As I have written, we will have to look at the memory issues from a more complex viewpoint than trying to fix random memory leaks reported by a proprietary tool.

**Comment by megacoderencoderdecoder** [comment]
@s3rvac also with DR.MEMORY i got error "**Reached maximum leak report limit (-report_leak_max). No further leaks will be reported.**" it found unreal big count of memory leaks...

**Comment by s3rvac** [comment]
I do not claim that you have not found any, nor do I claim that there are no memory leaks. I simply say that the current issue is useless for us. We know about the memory issues, and we will have to handle them in a more complex way.

**Comment by megacoderencoderdecoder** [comment]
```
ERRORS FOUND (by DrMemory):
      0 unique,     0 total unaddressable access(es)
     46 unique,    57 total uninitialized access(es)
      0 unique,     0 total invalid heap argument(s)
      0 unique,     0 total GDI usage error(s)
      0 unique,     0 total handle leak(s)
      0 unique,     0 total warning(s)
    984 unique, 61946 total, 6783472 byte(s) of leak(s)
     99 unique,   869 total, 729383 byte(s) of possible leak(s)
```
~60k memory leaks , 7MB memory leak for binary size 100kb
I think for binary 100mb this is value can be 1TB )))

**Comment by megacoderencoderdecoder** [comment]
@s3rvac i attach output for **retdec-llvmir2hll.exe** by DrMemory
[results.txt](https://github.com/avast/retdec/files/4194435/results.txt)
