### ISSUE TITLE
Constants error on simpilify load instruction

### ISSUE THREAD

**Issue by echo579** [avast/retdec#717]
# problem
currently constants pass will simpilify following code
```
-----------------------------------------------
>|   %38 = load i64, i64* @rax
	>|   %37 = load i64, i64* %stack_var_-40
		>|   %30 = load i64, i64* @rsi
			>| @rsi = internal global i64 0
-----------------------------------------------
```
into
```
-----------------------------------------------
>| @rsi = internal global i64 0
-----------------------------------------------
```
and will replace 
```
%40 = load i64, i64* %39
```
with 
```
%40 = load i64, i64* @rsi
```

following is all of the code

```
@rsi = internal global i64 0
%30 = load i64, i64* @rsi
store i64 %30, i64* %stack_var_-40
%37 = load i64, i64* %stack_var_-40
store i64 %37, i64* @rax
%38 = load i64, i64* @rax
%39 = inttoptr i64 %38 to i64*
%40 = load i64, i64* %39
```

obviously, it should be simpilified into

```
%38 = load i64, i64* @rsi
%39 = inttoptr i64 %38 to i64*
%40 = load i64, i64* %39
```
# solve
I guess optimization want to simpilify
```
load
store
load
```
into
```
load
```

This may need to check the instruction that defines load->getPointerOperand() is a store instruction.

**Comment by xkubov** [comment]
Hi, thank you for the report and effort to improve RetDec's output. We are aware that the current implementation responsible for constant propagation can be improved and currently we are working on it. Such changes and improvements should be part of the next release.

**Comment by echo579** [comment]
Thanks for your reply, looking forward to next release.
