### ISSUE TITLE
-instcombine generate unrecognized Intrinsic function

### ISSUE THREAD

**Issue by echo579** [avast/retdec#725]
I use retdec to decompile md5 algorithm and found instcombine will generate Intrinsic functions, such as llvm.fshl.i32.
```
  %77 = add i32 %71, %76, !insn.addr !79
  %78 = add i64 %67, ptrtoint (i32** @global_x to i64), !insn.addr !80
  %79 = inttoptr i64 %78 to i32*, !insn.addr !80
  %80 = load i32, i32* %79, align 4, !insn.addr !80
  %81 = call i32 @llvm.fshl.i32(i32 %77, i32 %77, i32 %80)
```
llvm.fshl.i32 is declared in .ll file
```
declare i32 @llvm.fshl.i32(i32, i32, i32) #0
```
But when I compile .bc or .ll file with clang. It occured with ```undefined reference to `llvm.fshl.i32'```.
Is there any idea to solve this problem.
Thanks
[md5.zip](https://github.com/avast/retdec/files/4333791/md5.zip)

**Comment by silverbacknet** [comment]
That functionality appeared in llvm 7, perhaps you have an older version?

Does retdec-decompiler.py produce the same output as manually running clang against them?

**Comment by echo579** [comment]
Thanks for your help, I find my clang version 6.0. Everything is okay with newer version.
