### ISSUE TITLE
Perhaps do a new release?

### ISSUE THREAD

**Issue by sophiawisdom** [avast/retdec#728]
It's been a year and [500 commits](https://github.com/avast/retdec/compare/v3.3...master) since the last release (v3.3). Maybe it's time to do another release? Otherwise it feels almost necessary to build it ourselves.

**Comment by s3rvac** [comment]
Hi! We definitely want to release a new version of RetDec, but we have not finalized the schedule yet. Stay tuned.

In the meantime, if you want to try the current `master`, feel free to use our [automated `master` builds](https://github.com/avast/retdec#automated-teamcity-builds) (Windows, Linux, macOS).

**Comment by s3rvac** [comment]
Just for completeness, we have released a new version of RetDec on 2020-04-07. Links:
* [Release](https://github.com/avast/retdec/releases/tag/v4.0)
* [Blog post](https://engineering.avast.io/retdec-v4-0-is-out/) describing the most important features

**Comment by sophiawisdom** [comment]
Thanks!
