### ISSUE TITLE
retdec-fileinfo fails with "Undefined symbol "_ZTVSt19bad_optional_access"" on FreeBSD

### ISSUE THREAD

**Issue by gwquk** [avast/retdec#752]
Hi,

I don't know enough about retdec to know what causing this issue is when executing

# /usr/local/bin/retdec-decompiler.py a.out

##### Gathering file information...
RUN: /usr/local/bin/retdec-fileinfo -c /root/Downloads/canon/a.out.config.json --similarity /root/Downloads/canon/a.out --no-hashes=all --crypto /usr/local/bin/../share/retdec/support/generic/yara_patterns/signsrch/signsrch.yara --crypto /usr/local/bin/../share/retdec/support/generic/yara_patterns/signsrch/signsrch.yarac --max-memory-half-ram
l**d-elf.so.1: Undefined symbol "_ZTVSt19bad_optional_access" referenced from COPY relocation in /usr/local/bin/retdec-fileinfo**

Thanks

**Comment by s3rvac** [comment]
Hi. I have almost no experience with FreeBSD (and RetDec supports it only experimentally via our community), but have you tried to re-build and re-install it? If that does not work, could you try a clean build and installation?

Also, what compiler and version do you use to build RetDec?

**Comment by gwquk** [comment]
Hi,
That's OK... I am still looking into it. I will install a fresh Virtualbox of FreeBSD ... and look into it.
BTW (unrelated) I may have found that the Firefox 75 (package) on both Linux (Centos 7) and FreeBSD 12.1p3 seems to have been compromised with what looks like a "backdoor"! If you are using Firefox I strongly suggest you install "Wireshark", scan the network and take a look. 
Regards

Greg
Ph: +44 1980 731 335
Mb: +44 771 3672 888 

    On Thursday, 23 April 2020, 11:58:28 am GMT+1, Petr Zemek <notifications@github.com> wrote:  
 
 


Hi. I have almost no experience with FreeBSD (and RetDec supports it only experimentally via our community), but have you tried to re-build and re-install it? If that does not work, could you try a clean build and installation?

Also, what compiler and version do you use to build RetDec?

**Comment by gwquk** [comment]
**Note: This had nothing to do with retdec on FreeBSD.**

SYMPTOMS:
- The reported error when try to run /usr/local/bin/retdec-decompiler.py
- Strange things were occurring on the file system, i.e. changes to files seem to magically revert to the previous version. 

FAULT:
The eventual fault diagnosis was a corrupted zfs pool on my FreeBSD machine.

FIXES (command line):
# zpool status
# zpool scrub zroot

The latter command advised of unrecoverable errors, zpool command advised to backup, recreate the zfs file systems and restore, which I did.

RESULT:
**retdec compiles & runs perfectly!** - with the updates I have made to the source code.

**Comment by s3rvac** [comment]
> with the updates I have made to the source code.

If they are fixes, could you please open a pull request with them? Maybe other people will also need them when building RetDec on FreeBSD. FreeBDS is currently supported only via community fixes (we only use Windows, Linux, and macOS).
