### ISSUE TITLE
retdec v4.0 --color-for-ida

### ISSUE THREAD

**Issue by ymg2006** [avast/retdec#762]
Hello there,
I wanted to use latest binaries from retdec v4.0 with IDA,
I get this error when executing IDA's plugin command, with v3.3 it's working fine. Please add back the --color-for-ida to v4.0 branch so we can use it.
retdec-decompiler.py: error: unrecognized arguments: --color-for-ida

For more information when I remove the --color-for-ida from CMD it run's perfectly and IDA load's source but it's monotonous codes in IDA.

The version I am currently using is:
ida: 7.2
retdec: 4.0
retdec-idaplugin: v0.9
python: 3.8.2

**Comment by PeterMatula** [comment]
See https://github.com/avast/retdec-idaplugin/issues/58 and https://github.com/avast/retdec-idaplugin/issues/59.
