### ISSUE TITLE
Do not consider section names generated by retdec-unpacker as unusual

### ISSUE THREAD

**Issue by metthal** [avast/retdec#775]
Our unpacker uses `gu_idata` and `gu_rsrc` section names to reconstruct the binary file. These section names are however recognized as unusual by anomaly detector what shouldn't happen since we shouldn't consider something as an anomaly whenever we've generated it ourselves.

**Comment by ladislav-zezula** [comment]
https://github.com/avast/retdec/pull/776
https://github.com/avast/retdec-regression-tests/pull/64
