### ISSUE TITLE
v4.0 Not able to detect VMProtect file

### ISSUE THREAD

**Issue by sooxt98** [avast/retdec#780]
im using the file from here
https://github.com/avast/retdec-regression-tests/commit/cf136e919b1392a27f259d98e2dd607ba55ea9ec

and the result
![image](https://user-images.githubusercontent.com/13378059/83671230-eb8b2200-a606-11ea-9e2d-3f055bcc621c.png)

**Comment by s3rvac** [comment]
Hi. RetDec v4.0 was released on 2020-04-07, but that detection of VMProtect was added a week later, on 2020-04-14 (#734). You will need to use the current `master` ([here](https://github.com/avast/retdec#automated-teamcity-builds) are pre-built binaries).

Here is the output of `retdec-fileinfo` in the current `master`:
```
$ retdec-fileinfo VMProtect-3.4_demo.ex
Input file               : VMProtect-3.4_demo.ex
[..]
Endianness               : Little endian
Image base address       : 0x10000000
Entry point address      : 0x100c5fba
Entry point offset       : 0x3dba
Entry point section name : .rcp3
Entry point section index: 9
Bytes on entry point     : 9cc70424f6d3fc0ce964deffff0f84b7b50b000f83d2030000f5f9f9f980fc0555e9182c01008b4c243ce8ecee000087fe89
Detected tool            : VMProtect (2.04+) (packer), combined heuristic
Detected tool            : Microsoft Linker (10.0) (linker), combined heuristic
Detected tool            : Microsoft (linker), dos header style
[..]
```
