### ISSUE TITLE
What is the easiest way to recompile the C output file from retdec?

### ISSUE THREAD

**Issue by smabie** [avast/retdec#786]
So i'm just playing around with retdec on some test executables and was wondering what's the easiest way to recompile the C file? Is there any easy way to get all of the dynamic libraries used and such to generate the exact command-line options needed for llvm/gcc?

Thanks!

**Comment by s3rvac** [comment]
Hi. TLDR: Unfortunately, in general, there is no such way. Don't try re-compiling RetDec's output as it won't work in most cases.

Longer story and rationale: https://github.com/avast/retdec/issues/563 (see also https://github.com/avast/retdec-idaplugin/issues/62).
