### ISSUE TITLE
Add option to disable color output

### ISSUE THREAD

**Issue by rfalke** [avast/retdec#791]
Either a command line option or an option in the JSON config file or when output doesn't go to a tty (like a file).

**Comment by xkubov** [comment]
Hi, so you are interested in the output log of the decompiler? I agree that it might be useful and RetDec should also contain some kind of control mechanism for the output - e.g. silent/verbose decompilation. What do you think @PeterMatula?

**Comment by rfalke** [comment]
I store the output log in https://github.com/rfalke/decompiler-subjects to help others understand what the decompiler "thinks". 

For retdec I used a sed to strip the ansi sequences (see https://github.com/rfalke/decompiler-subjects/blob/master/scripts/update_retdec.sh). Since (from my POV) there is a solution I thing the issue can be low-prio. On the other side is a simple switch also easy to implement.

I'm not interested in more elaborated stuff like silent/verbose.

**Comment by xkubov** [comment]
RetDec now automatically detects if the output is printed to console or is redirected to file. This should be what you want. If you have a problem with this feature or you would like a different behavior you can open a new issue.
