### ISSUE TITLE
Boolean expression hard to understand

### ISSUE THREAD

**Issue by rfalke** [avast/retdec#798]
Subject: https://github.com/rfalke/decompiler-subjects/tree/master/from_holdec/dmi/exp/ia32_elf/subject.exe

Output
```
int32_t advanced_1_boolean_minization(int32_t a1, int32_t a2, int32_t a3) {
    if ((a2 || a1) == 0 == (a3 != 0)) {
        // 0x804865e
        return 1;
    }
    if (a3 != 0 == (a1 == 0 && a2 != 0)) {
        // 0x804865e
        return 1;
    }
...
```

gcc correctly points out
```
a.c: In function ‘advanced_1_boolean_minization’:
a.c:4:20: warning: suggest parentheses around comparison in operand of ‘==’ [-Wparentheses]
     if ((a2 || a1) == 0 == (a3 != 0)) {
         ~~~~~~~~~~~^~~~
a.c:8:12: warning: suggest parentheses around comparison in operand of ‘==’ [-Wparentheses]
     if (a3 != 0 == (a1 == 0 && a2 != 0)) {
         ~~~^~~~
```

**Comment by xkubov** [comment]
Hi, thank you for the report. In this situation, however, I don't think that this is a problem that needs to be solved by the decompiler. As this is not a specific problem and I think that the only solution would be putting parentheses everywhere - which would probably result in much worse results overall. What do you think @PeterMatula. I am going to close this issue for now but we can continue to have a discussion regarding this in here.

**Comment by rfalke** [comment]
Ok what about not generating such strange expressions on the first place?! I would expect something like 
```
if(a1==0 && a2!=0 && a3 != 0) // not sure if this is equivalent but you get the point
```
to read and not this complex and strange expression.
