### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by Orneeman** [avast/retdec#814]
Hi ,
I am trying to decompile Arm64 so but I got out of memory error, any way to slove it?
![image](https://user-images.githubusercontent.com/38044916/87681090-ee8d3c80-c786-11ea-8fe5-a6c0e72b11bb.png)

**Comment by xkubov** [comment]
Hi, by default RetDec uses only a maximum of half of your system RAM for the decompilation. If you want to change the behavior, you can specify `--max-memory MAX_MEMORY` or `--no-memory-limit` parameters of `retdec-decompiler` executable.

**Comment by Orneeman** [comment]
so its crash because its too low, is it possible that I don't have enough memory to decompile this so file ( 8Mb)?
Thanks

**Comment by xkubov** [comment]
When you remove the limit with parameter `--no-memory-limit` decompilation should continue and RetDec will try further and won't be stopped at decompilation limit. This might, however, take a lot of memory and time - your computer might start caching intensively. More about memory issues can be found at #13.

**Comment by Orneeman** [comment]
Thanks :)
