### ISSUE TITLE
retdec-fileinfo allocates 4 GB to read the debug directory of a 2.7 MB file

### ISSUE THREAD

**Issue by s3rvac** [avast/retdec#824]
`retdec-fileinfo` allocates 4 GB to read the debug directory of a 2.7 MB file.

**Steps to reproduce**

```
$ /usr/bin/time -v retdec-fileinfo FILE
```
where `FILE` is [022AFB79C539B23AECFAD315C7D9A712D747B521952184446026F7F2AA9005B8](https://www.virustotal.com/gui/file/022afb79c539b23aecfad315c7d9a712d747b521952184446026f7f2aa9005b8/detection).

**Expected output**

`retdec-fileinfo` allocates a reasonable amount of memory to analyze the above 2.7 MB file.

**Actual output**

```
[..]
Maximum resident set size (kbytes): 4211072
[..]
```
which is around 4 GB of used RAM.

**Analysis**

[Here](https://github.com/avast/retdec/files/4975546/022AFB79C53-massif-output.zip) is an output from `valgrind --tool=massif` (a heap profiler). Below, you can also find a screenshot from `massif-visualizer`:

![022AFB79C53-massif-visualizer](https://user-images.githubusercontent.com/5675953/88457449-ca1c1900-ce86-11ea-8dcd-334ed2935f89.png)

As can be seen from the output, in `DebugDirectory::read()`, a `std::vector` is resized to 4 GB. This happens in `src/pelib/DebugDirectory.cpp` on line 49:
```cpp
47             // Load the debug info data from the file, not from the image.
48             // Some samples may have debug info part of the overlay
49             debugEntry.data.resize(debugEntry.idd.SizeOfData);
```
For the above file, `debugEntry.idd.SizeOfData` is `4294967295` (`UINT_MAX`). 

**Notes**

* I suggest verifying whether there is an overflow (the value would suggest that).
* When fixing the issue, please add the file into our regression-tests suite. We can just check that the analysis finishes successfully. We will at least have this file in the test suite.

**My configuration**

* Current `master` (commit 956b1a3f2f18283662757c081d6b8b3c52dcd6b1)
* 64b Debian, GCC 9, Debug build

**Comment by ladislav-zezula** [comment]
https://github.com/avast/retdec/pull/825
