### ISSUE TITLE
[Question] how to run retdec-decompiler mutithreaded?

### ISSUE THREAD

**Issue by miz2019** [avast/retdec#826]
It seems that retdec-decompiler execution is singlethreaded, and process a ~30M binary could take hours.
I wonder if 
1: there is method to run, and should invoke the command in a specific manner/option.
2: just a feature not implemented yet.
3: which is technical difficult hard to overcome. It seems much parallel execution opportunities between functions, do I think it too simple?
 
Thanks.

**Comment by s3rvac** [comment]
Hi. I am closing this ticket in favor of #292, which is a feature request for adding support for multi-threading into RetDec. Please, see it and #51 for more details.

**Comment by miz2019** [comment]
OK, thanks.
