### ISSUE TITLE
Update frontpage documentation

### ISSUE THREAD

**Issue by daveime68** [avast/retdec#859]
Nowhere is it specified that Python needs to be installed on the system, or that the process must now be launched with retdec-decompiler.py FILENAME

**Comment by s3rvac** [comment]
Hi! Which RetDec release do you use? The `retdec-decompiler.py` script does no longer exist, which is why it is not mentioned in the README (this is what I believe you have meant by _frontpage documentation_).

**Comment by s3rvac** [comment]
Anyway, [here](https://github.com/avast/retdec/tree/v4.0#retdec) is a README for the latest release: v4.0.

**Comment by s3rvac** [comment]
I have created a ticket for re-considering the purpose of the main README: #860. One option is to make it up-to-date with the current release (it is currently up-to-date with `master`, which is where the development happens). Another option is to mention that it concerns the current `master` and provide links to READMEs corresponding to releases.

I am closing this ticket. If you have any remarks, feel free to mention them in #860.
