### ISSUE TITLE
x87: strange modelling of fpatan as __asm_fpatan with only one parameter

### ISSUE THREAD

**Issue by rfalke** [avast/retdec#886]
Subject: https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/i386_x87_fpu/ia32_elf/subject.exe
Output:
```
int32_t FPATAN(int32_t a1) {
    float64_t v1 = __asm_fpatan(1.0L / (float80_t)(float64_t)(int64_t)a1); // 0x804ab1b
    printf("FPATAN(y=1 x=para): should=                             is=%12f/%15e\n", v1, v1);
    float64_t v2 = __asm_fpatan(INFINITY); // 0x804ab38
    printf("FPATAN(y=1 x=0):    should=    1.570796/   1.570796e+00 is=%12f/%15e\n", v2, v2);
    float64_t v3 = __asm_fpatan(1.0L); // 0x804ab55
    printf("FPATAN(y=1 x=1):    should=    0.785398/   7.853982e-01 is=%12f/%15e\n", v3, v3);
    return 0;
}
```

Providing x=0 is a valid use case. Of course `__asm_fpatan` can be implemented to understand +inf and -inf but it looks like an odd decision.

**Comment by PeterMatula** [comment]
Can you elaborate on this?

`fpatan` is currently modeled like this:
```
x = st(0)
y = st(1)
z = fdiv y, x
r = __asm_fpatan(z)
st(1) = r
```
It looks like in 2 out of these 3 cases some analysis (most likely some LLVM opt pass) was able to evaluate the operands (i.e. `1/0`, `1/1`). I don't know if this is correct evaluation.

Looking at the specification again, I think it could be more simple and foolproof to ditch the division and just do something like:
```
x = st(0)
y = st(1)
r = __asm_fpatan(y, x)
st(1) = r
```
Is this what you mean? If so, this is really easy fix.

**Comment by PeterMatula** [comment]
Yes, It think that's what you meant. And I like it, so I fixed it. Now the output looks like this:
```c
    float64_t v1 = __asm_fpatan(1.0L, (float80_t)(float64_t)(int64_t)a1); // 0x804ab1b
    printf("FPATAN(y=1 x=para): should=                             is=%12f/%15e\n", v1, v1);
    float64_t v2 = __asm_fpatan(1.0L, 0.0L); // 0x804ab38
    printf("FPATAN(y=1 x=0):    should=    1.570796/   1.570796e+00 is=%12f/%15e\n", v2, v2);
    float64_t v3 = __asm_fpatan(1.0L, 1.0L); // 0x804ab55
    printf("FPATAN(y=1 x=1):    should=    0.785398/   7.853982e-01 is=%12f/%15e\n", v3, v3);
```
