### ISSUE TITLE
retdec-fileinfo runs over a minute and uses 40 GB of RAM to analyze a 46 MB PE file

### ISSUE THREAD

**Issue by s3rvac** [avast/retdec#911]
`retdec-fileinfo` runs over a minute and uses 40 GB of RAM to analyze a 46 MB PE file

## Steps to reproduce

On Linux, run
```
$ /usr/bin/time -v retdec-fileinfo FILE
```
where `FILE` is `93BFA7B15B780AC44C0500C127DACC2B69C29AEC94FB2F63D684F68DF4A40F5C`.

## Expected output

The file is analyzed in a reasonable time and using a reasonable amount of memory.

## Actual output

```
$ /usr/bin/time -v retdec-fileinfo FILE
[..]
        User time (seconds): 88.79
[..]
        Maximum resident set size (kbytes): 42310212
```
That is, `retdec-fileinfo` ran for over a minute and used around 40 GB of memory during the analysis.

## Configuration

* Commit: ec5cd887e0262c250b128507384c1ad75a82972e (current `master`, including a fix for #907)
* 64b Debian Buster, GCC 9, Debug build of RetDec

**Comment by ladislav-zezula** [comment]
https://github.com/avast/retdec/pull/912
