### ISSUE TITLE
Very damaged/truncated PE is reported as unsupported format

### ISSUE THREAD

**Issue by metthal** [avast/retdec#921]
We were previously reporting for a very damaged PE files that they are PEs with a loader errors. For example such file is `7c9435ecd691de2a53e0d4ca32f3ae57725a248fe3d86230efadefd131029eb2`. As of right now, we are reporting it as an unsupported file format.

Don't have it confirmed but it seems like #812 might be a breaking point where regression was introduced. We'd like to reporting this as a very broken PE instead of unsupported file format.

**Comment by ladislav-zezula** [comment]
I slightly changed the logic:

- Before: The image loader in fileinfo set `ldrError` to `LDR_ERROR_NTHEADER_OUT_OF_FILE` and returned `ERROR_INVALID_FILE`
- After: The image loader sets `ldrError` to `LDR_ERROR_NTHEADER_OUT_OF_FILE` and returns `ERROR_NONE`.

As result, the first phase check now recognizes the file as PE and the final status is `LDR_ERROR_NTHEADER_OUT_OF_FILE`.

https://github.com/avast/retdec/pull/922
https://github.com/avast/retdec-regression-tests/pull/83

**Comment by s3rvac** [comment]
Fixed in #922.
