### ISSUE TITLE
RetDec tries to decompile to LLVM code even though I'm not using LLVM?

### ISSUE THREAD

**Issue by zurgeg** [avast/retdec#940]
Hi,

Sorry if I'm using RetDec wrong, but I'm attempting to decompile a GameCube game. The DOL file contains all of the information that I pass to retdec, and I removed the header and passed in the required data, however, I ran into one problem:
RetDec will not stop trying to decompile for LLVM!

This may be caused by the fact it detects it was compiled with XCode (it wasn't, it was compiled with codewarrior):
```
Input file               : C:\Users\user\OneDrive\Documents\Disassemblies\raw.dol
File format              : Raw Data
File type                : Executable file
Architecture             : PowerPC
Endianness               : Big endian
Entry point address      : 0xc351f
Entry point offset       : 0xc351f
Entry point section name : .text
Entry point section index: 0
Bytes on entry point     : 354803f8fd8801002880a1002c2800000040820014386101bc48277fa138600000480001ec7ee4bb78386102084803f92180
Detected tool            : XCode with OS X SDK (compiler), 21 from 88 significant nibbles (23.8636%)
```

So, I have 2 questions:
1. How can I force RetDec to decompile for not LLVM?
2. How can I force RetDec to detect I'm using CodeWarrior?

Additionally, the GameCube uses PPC Gekko (the GameCube variant of PPC) which may be messing with it, but I have my doubts that that's happening here.

If needed, I can pass in an assembly file with linker script, which I would assume would make it easier on RetDec (because the disassembled file was done with a disassembler that was built for PPC Gekko).

**Comment by zurgeg** [comment]
Alright, so I figured out that there is a tool to convert a GameCube DOL file to an ELF file, which **should** make it work, I will have to try later

**Comment by silverbacknet** [comment]
It's not detecting CodeWarrior/GC because it's not finding one of these patterns: https://github.com/avast/retdec/blob/master/support/yara_patterns/tools/elf/ppc64/compilers.yara

If you find a good pattern, you can recompile just the patterns and it should immediately stop thinking XCode has anything to do with it.

**Comment by KOLANICH** [comment]
LLVM and its infrastructure is used as an internal representatiin. All compilers and decompilers have internal representation. This one just utilizes LLVM one to be able to utilize LLVM optimization machinery. Also it gives interoperability with other tools using LLVM.

I guess this issue should be closed.

**Comment by zurgeg** [comment]
Yeah, I'm not really working on the project I needed this for anymore either.
