### ISSUE TITLE
Do not provide entry point offset in case it doesn't exist

### ISSUE THREAD

**Issue by metthal** [avast/retdec#962]
In files like `ba0b32b812b8bd25b1481f25e1ab37663611e87c73e9f15f6a9c442a97add916`, entry point is set to section which is pure in-memory section and doesn't contain any data on disk. However we try to calculate entry point offset for sections like these while it doesn't make sense because reaching into a file at that offset doesn't lead to anything.

Please make it so that entry point address is first checked for the actual presence on the disk (using section headers) before it is calculated into offset and not provided in such case.

**Comment by HoundThe** [comment]
I am not sure if I understand the proposed enhancement fully. 

In case the entry point is set to a location outside any section that is actually physically in the file (not pointing to a valid section located in a file), then FileInfo should not export any Entry Point Address or Entry Point Offset?
