### ISSUE TITLE
retdec-fileinfo detects .NET structures that do not belong to the binary itself, but to embedded binary

### ISSUE THREAD

**Issue by ladislav-zezula** [avast/retdec#967]
Samples:

- ae5caf6428c005bdf7aa2ce88a672ec62e1b0fdeba9fa43aceeb8e00aca73bbf
- 76360c777ac93d7fc7398b5d140c4117eb08501cac30d170f33ab260e1788e74

In both binaries, `retdec-fileinfo` shows .NET structures. Sadly, these don't belong to the binary(ies) itself, but to a binary that is embedded in the resources.

**Comment by ladislav-zezula** [comment]
https://github.com/avast/retdec/pull/970

**Comment by PeterMatula** [comment]
Fixed in #970.
