### ISSUE TITLE
PE signature needs to be outside of the image to be considered valid

### ISSUE THREAD

**Issue by metthal** [avast/retdec#972]
Signatures in PE files needs to be outside of the image to be considered valid. These files contain signatures in their last section  and Windows doesn't see them at all. Please make it so that this is actually checked for.

```
026ca63f4f1364726b32af8d6e628172dcffc36405c4e09a140bf422045c743b
c4b9677e1a4795d99a18354771a32b50574c1e74df8393828d26f922bac1c8ef
```

**Comment by HoundThe** [comment]
I am thinking about how to include this in the output, that the signature is outside of the image and thus invalid. Would an extra "isValid" member be sufficient or maybe something more specific "isOutsideImage"?
